Именения в проекте. Счетчик не смог сделать. Не понимаю как. Когда переношу весь ввод в main, то выбивает ошибку AttributeError: partially initialized module 'reciept' has no attribute 'Reciept' (most likely due to a circular import)